### ISSUE TITLE
Package fails to build due to avatar size being to large.

### ISSUE THREAD

**Issue by alexpeterson91** [androolloyd/DAppNodePackage-otterscan#6]
**Describe the bug**
package fails dappnodesdk build 
` DAppNodePackage-otterscan % dappnodesdk build
  ✔ Verify connection
  ✔ Create release dir
  ✖ Copy files and validate
    → Avatar png must be a square (1:1) between 200 and 300 px wide, but it's 34
…
    Build architecture linux/amd64
    Upload release to IPFS node
    Save upload results
 ✖ Wrong avatar aspect size
Avatar png must be a square (1:1) between 200 and 300 px wide, but it's 341 x 341

`

**To Reproduce**

**Expected behavior**
Should continue with build when resized

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**
more issues once this is fixed.

**Comment by androolloyd** [comment]
i pushed a new version with otterscan updates today
